"""Нормализация команд Telegram без бизнес-логики."""

from __future__ import annotations

from typing import Optional

COMMAND_ALIASES = {
    "/today": "/today",
    "/brief": "/brief",
    "/day": "/day",
    "/meetings": "/meetings",
    "/tasks": "/tasks",
    "/weather": "/weather",
    "/search": "/search",
    "/web": "/web",
    "/find": "/find",
    "/plan-day": "/plan-day",
    "/plan": "/plan",
    "/topics": "/topics",
    "/posts": "/posts",
    "/ideas": "/ideas",
    "/draft": "/draft",
    "/write-post": "/write-post",
    "/harder": "/harder",
    "/softer": "/softer",
    "/business": "/business",
    "/whoop": "/whoop",
    "/health": "/health",
    "/repair": "/repair",
    "/sales": "/sales",
    "/pipeline": "/pipeline",
    "/risks": "/risks",
    "/focus-sales": "/focus-sales",
    "/finance": "/finance",
    "/pnl": "/pnl",
    "/cashflow": "/cashflow",
    "/runway": "/runway",
    "/expenses": "/expenses",
    "/clients-profit": "/clients-profit",
    "/ar": "/ar",
    "/ap": "/ap",
    "/finance-risks": "/finance-risks",
    "/bitrixcheck": "/bitrixcheck",
    "сегодня": "/today",
    "бриф": "/brief",
    "день": "/day",
    "встречи": "/meetings",
    "задачи": "/tasks",
    "погода": "/weather",
    "поиск": "/search",
    "найди": "/search",
    "поищи": "/search",
    "search": "/search",
    "web": "/web",
    "план": "/plan",
    "темы": "/topics",
    "посты": "/posts",
    "идеи": "/ideas",
    "topics": "/topics",
    "posts": "/posts",
    "ideas": "/ideas",
    "пост": "/draft",
    "черновик": "/draft",
    "draft": "/draft",
    "write-post": "/write-post",
    "harder": "/harder",
    "softer": "/softer",
    "business": "/business",
    "жестче": "/harder",
    "мягче": "/softer",
    "бизнес": "/business",
    "здоровье": "/whoop",
    "статус": "/health",
    "система": "/health",
    "health": "/health",
    "repair": "/repair",
    "почини": "/repair",
    "ремонт": "/repair",
    "продажи": "/sales",
    "sales": "/sales",
    "воронка": "/pipeline",
    "pipeline": "/pipeline",
    "риски": "/risks",
    "фокус": "/focus-sales",
    "focus-sales": "/focus-sales",
    "финансы": "/finance",
    "финансист": "/finance",
    "finance": "/finance",
    "pnl": "/pnl",
    "опиу": "/pnl",
    "ддс": "/cashflow",
    "cashflow": "/cashflow",
    "runway": "/runway",
    "расходы": "/expenses",
    "маржа": "/finance-risks",
    "клиенты-прибыль": "/clients-profit",
    "дебиторка": "/ar",
    "кредиторка": "/ap",
    "касса": "/cashflow",
    "финриски": "/finance-risks",
    "bitrixcheck": "/bitrixcheck",
    "битрикс": "/bitrixcheck",
}


def extract_command(text: str | None) -> Optional[str]:
    raw_text = str(text or "").strip().lower()
    if not raw_text:
        return None
    token = raw_text.split()[0]
    return COMMAND_ALIASES.get(token)
