"""Контракт bridge-runtime для Sales / Lev."""

from __future__ import annotations

from shared.contracts.sales_report_contract import SALES_RUNTIME_REPORT_TYPES

REPORT_TYPES = set(SALES_RUNTIME_REPORT_TYPES) | {"bitrixcheck"}

REMOTE_ENV_KEYS = {
    "BITRIX_CLIENT_ID",
    "BITRIX_CLIENT_SECRET",
    "BITRIX_OAUTH_TOKEN_URL",
    "BITRIX_TIMEOUT_SEC",
    "WAZZUP_API_KEY",
    "WAZZUP_API_BASE_URL",
    "TELEGRAM_BOT_TOKEN",
    "TELEGRAM_CHAT_ID",
    "TELEGRAM_OWNER_ID",
    "TELEGRAM_API_BASE_URL",
    "TELEGRAM_DRY_RUN",
    "SALES_TELEGRAM_BOT_TOKEN",
    "SALES_TELEGRAM_CHAT_ID",
    "SALES_WEEKLY_TELEGRAM_CHAT_ID",
    "SALES_TELEGRAM_OWNER_ID",
    "SALES_TELEGRAM_API_BASE_URL",
    "SALES_TELEGRAM_BOT_TOKEN_FILE",
    "SALES_TELEGRAM_DRY_RUN",
    "SALES_INACTIVITY_DAYS",
    "SALES_LATE_STAGE_INACTIVITY_DAYS",
    "SALES_LARGE_DEAL_AMOUNT",
    "SALES_MONTHLY_TARGET",
    "SALES_DEPARTMENT_IDS",
    "SALES_DEPARTMENT_NAMES",
    "SALES_EXCLUDED_USER_IDS",
    "SALES_EXCLUDED_USER_NAMES",
    "SALES_EXCLUDED_USER_MARKERS",
}
